### ISSUE TITLE
Error in the funnel reports

### ISSUE THREAD

**Issue by RodolfoPichardo** [Open-Web-Analytics/Open-Web-Analytics#259] opened 2017-06-27 20:02 UTC
Using the most recent code (master), the following PHP errors appear when accessing the funnel reports:

```
Notice: Undefined offset: 0 in /{OWA_DIR}/modules/base/reportGoalFunnel.php on line 98
Notice: Undefined offset: 0 in /{OWA_DIR}/modules/base/reportGoalFunnel.php on line 99
```

Also the images don't appear in those reports.

**Comment by Maaiins** [comment] 2020-03-27 09:44
@padams Could not reproduce in Version 1.6.6. Looks like an incomplete installation.

**Comment by padams** [comment] 2020-04-04 20:01
me neither. Closing.

**Closed by padams** 2020-04-04 20:01 UTC
Labels: Review needed, debug info needed
