### ISSUE TITLE
Unable to update new WP installation

### ISSUE THREAD

**Issue by goaliemn** [Open-Web-Analytics/Open-Web-Analytics#525] opened 2020-04-09 19:28 UTC
I used the pre-packaged owa.  Installed it and when selecting the dashboard, it said “core” had to be updated and use the cli to do it.  I attempted to install but it wasn’t able to find the db info.  It looks like the plugin hadn’t written any host info for the cli to read when doing the update.  Is there a way around this?

**Comment by padams** [comment] 2020-04-09 20:08
Which version of OWA are you running? If it is a fresh install there i no need to update anything. Did you follow the directions on the wiki for WordPress?

**Comment by goaliemn** [comment] 2020-04-09 21:11
1.6.6
 

 
I did follow the wiki

**Comment by emanueleg** [comment] 2020-04-09 21:59
I confirm the issue - tried a fresh install of OWA 1.6.6 on WP 5.4 and got same problem following wiki's instructions.
Then I tried OWA 1.6.4 and everything worked as expected.

**Comment by padams** [comment] 2020-04-09 22:26
Few more questions....

- What version of PHP are you running?

- Is the install from the owa_1.6.6_packaged.tar?

- Where and when are you guys seeing this error? 

- is OWA writing out it’s OWA-config.php?

**Comment by goaliemn** [comment] 2020-04-09 22:38
7.4
Yes
As soon as I try to access owa dashboard
No. It doesn't appear to get that far

**Comment by padams** [comment] 2020-04-09 22:41
Make sure the OWA directs has the proper permissions (ie. is writable) and then deactivate the plugin in Wordpress and then re-activate it. Upon re-activation OWA should do the install steps it missed if the directory was not writable. 

Also check the owa-data/logs/errors_xxxx file to see specifically what OWA is saying about the install.

**Comment by goaliemn** [comment] 2020-04-09 22:47
done.  here's the error log from when I tried running the cli update

12:17:18 2020-04-09 12940 [debug_log] Applying Update 3 
(owa_base_003_update)
12:17:18 2020-04-09 12940 [debug_log] Pre Update Proceadure Suceeded

Otherwise I'm still getting the error screen that says:


Some Modules need to create or update their database tables.

Here is the list of modules that have updates that needs to be applied:

base
It is recommended that you backup your database before applying updates.

**Comment by padams** [comment] 2020-04-09 22:48
are you by chance updating fro ma very old install of OWA?

**Comment by goaliemn** [comment] 2020-04-09 22:49
its a clean install.  Never had it installed before.  It looks like 
someone else encountered the same error..

**Comment by padams** [comment] 2020-04-09 23:00
ok hanks guys. This is a bug. Let me patch it.

**Comment by padams** [comment] 2020-04-10 00:25
Should now be fixed in v1.6.7.

**Comment by goaliemn** [comment] 2020-04-10 00:52
I’m getting a plugin has caused a fatal error.. I used the 1.6.7 package tar file.  I move the owa directory and it clears

**Comment by padams** [comment] 2020-04-10 00:57
strange. make sure you replace the _entire_ owa directory with the files from the new version. then just try and re-install/activate the plugin via the Wordpress plugs page.

**Comment by goaliemn** [comment] 2020-04-10 00:58
I did.  Same error.  Older version does work ok as listed by other contributor to thread

**Comment by padams** [comment] 2020-04-10 01:04
I can't reproduce the issue any longer with 1.6.7.... try a different browser in case there is some wacky caching going on.

**Comment by emanueleg** [comment] 2020-04-10 08:51
Hi, I confirm the issue with release 1.6.7. From my apache2 log:
PHP Fatal error:  Uncaught Error: Class 'photopress_util' not found in /var/www/gpgwp/wp-content/plugins/owa/wp_plugin.php.

Reproduced on apache2.4 - php 7.0.33 - WP 5.4

I'm attaching the stack trace if it helps:
Stack trace:\n#0 /var/www/gpgwp/wp-content/plugins/owa/wp_plugin.php(1616): owa_wp_settings_section->__construct(Array)\n#1 /var/www/gpgwp/wp-content/plugins/owa/wp_plugin.php(1283): owa_wp_settingsPage->registerSection(Array)\n#2 /var/www/gpgwp/wp-includes/class-wp-hook.php(285): owa_wp_module->registerSettings()\n#3 /var/www/gpgwp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)\n#4 /var/www/gpgwp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)\n#5 /var/www/gpgwp/wp-admin/admin.php(170): do_action('admin_init')\n#6 /var/www/gpgwp/wp-admin/plugins.php(10): require_once('/var/www/gpgwp/...')\n#7 {main}\n  thrown in /var/www/gpgwp/wp-content/plugins/owa/wp_plugin.php on line 2392

BTW not a real bug, but latest release owa_1.6.7_packaged.tar includes also owa_1.6.6_packaged.tar - maybe a forgotten old file inside the dev folder? :-)

**Comment by padams** [comment] 2020-04-10 16:22
ah! Thank you. Will get a fix shortly.

**Comment by padams** [comment] 2020-04-10 20:07
ok v.1.6.8 is there now. thanks all.

**Comment by padams** [comment] 2020-04-10 20:31
I'm closing this but re-open if there are still problems.

**Closed by padams** 2020-04-10 20:31 UTC
Labels: Installation, WordPress, bug

**Comment by emanueleg** [comment] 2020-04-10 20:40
I confirm the bug has been solved in v1.6.8.
Thank you!
