### ISSUE TITLE
Login impossible from Chrome

### ISSUE THREAD

**Issue by josephernest** [Open-Web-Analytics/Open-Web-Analytics#210] opened 2016-11-25 14:37 UTC
I cannot log in with Chrome 54, Windows 7. 

Server:  Debian 8 / PHP 5.5.9-1ubuntu4.7

Once the password is entered, the login / password fields get blank again and no login happens.
(If I enter a wrong password, I get an error. If I enter the correct password, the fields get blank).

It works on FF. Maybe linked to https://github.com/padams/Open-Web-Analytics/issues/93.

**Comment by ThePrudentNinja** [comment] 2016-12-16 16:36
Not a fix but I noticed the same issue from Chrome 55 from Linux. Create a bookmark pointing to some area inside OWA you want. To login, go to the bookmark, login, then the black page shows, click the bookmark again and it works.

**Comment by padams** [comment] 2018-02-21 19:45
Is anyone able to step through this with development logging turned on and see where the error is int he logs?

**Comment by mbrown1413** [comment] 2018-02-21 21:02
[Here are the log files](https://gist.github.com/mbrown1413/36b29a46c6209c5d8759ed6f2347e55d)

I included the log for both Chrome and Firefox. No adblockers or any weird extensions on Chrome. The login seems to succeed, especially because when I type an incorrect password it shows a message saying the password was incorrect.

**Comment by padams** [comment] 2018-02-23 03:13
You need to run OWA under a fully qualified domain. Add an alias in your /etc/hosts file if you are doing local development. Also try running under port 80. I don't know why, but the use of a port might also be confusing things.

**Comment by homeserverinc** [comment] 2019-03-27 17:14
Any news about this issue?

I'm running version 1.6.2 under a production server, with an FQDN (a sub-domain in fact), and under port 443 (SSL Let's Encrypt).

I personally not a big fan of the Firefox, and today after a few days without accessing the system, I've forgotten this issue, and try for a few times under chrome until release that the problem was not my credentials, but the browser.
If can help, under chrome running on my Android device works perfectly. In my laptop running Ubuntu 18.10 and Chrome 71.0.3578.98 does not work.

**Comment by Maaiins** [comment] 2020-03-27 09:30
@padams Couldn´t reproduce this bug.

Using:
Apache 2.2
PHP 7.1
Using Subdomain with Let´s Encrypt certificate
Open Web Analytics Version 1.6.6
Chrome 80.0.3987.149

**Comment by padams** [comment] 2020-04-04 20:04
ok. closing. feel free to reopen if anyone can come up with a more specific bug.

**Closed by padams** 2020-04-04 20:04 UTC
Labels: Review needed, bug
